# Generated by Django 5.2.5 on 2025-08-13 21:01

import django.core.validators
import django.db.models.deletion
import localflavor.us.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$', 'Please format the phone number as XXX-XXX-XXXX.')])),
                ('street_address', models.CharField(max_length=1024, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('state', localflavor.us.models.USStateField(max_length=2, null=True)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10, null=True)),
                ('payment_method', models.CharField(choices=[('', 'Not Paid'), ('cash', 'Cash'), ('check', 'Check'), ('paypal', 'PayPal'), ('venmo', 'Venmo')], default='', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
